import { Inter, Archivo } from 'next/font/google';
import './globals.css';
import Nav from '@/Components/Nav';
import Footer from '@/Components/Footer';

const archivo = Archivo({ subsets: ['latin'] });

export const metadata = {
  title: 'D-Pyramid',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${archivo.className} bg-[#f8f8f8]`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
